# Generated by Django 4.1.5 on 2023-02-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_header_image_post_image1_post_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, default='', upload_to='posts/%Y/%m/%d/'),
        ),
    ]
